FROM node:18-alpine

ARG NPM_TOKEN
ENV NPM_TOKEN=$NPM_TOKEN

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh python3 make g++ libexecinfo-dev
WORKDIR /server
COPY . /server

# bump npm version
RUN npm i -g npm@8.3

RUN npm ci
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
