FROM node:lts-alpine

ARG NPM_TOKEN
ENV NPM_TOKEN=$NPM_TOKEN

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh python make g++ libexecinfo-dev
WORKDIR /server
COPY . /server

RUN npm ci
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
